name: Android CI

on:
  push:
    branches: [ aide-legacy ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK (cmdline tools only)
        uses: android-actions/setup-android@v3

      - name: Install SDK packages (explicit path)
        shell: bash
        env:
          SDKMANAGER: ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin/sdkmanager
        run: |
          set -x
          ( yes | "$SDKMANAGER" --licenses ) || true
          "$SDKMANAGER" --install "platform-tools"
          "$SDKMANAGER" --install "platforms;android-31"
          "$SDKMANAGER" --install "build-tools;31.0.0"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
