name: Sanity CI

on:
  push:
    branches: [ aide-legacy ]
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hi
        run: echo "Workflow parses and runs ✅"
